/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentalmobil;
import rentalmobil.Package.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nurka
 */
public class AdminPage extends javax.swing.JFrame {
    
    private Pegawai data;
    private PegawaiModel pegawai;
    private UsersModel users;
    private MobilModel mobil;
    private PeminjamanModel peminjaman;
    private String id;

    public void setId(String id) 
    {
        this.id = id;
        
        startup();
    }
       
    /**
     * Creates new form AdminPage
     */
    public AdminPage() {      
        data = new Pegawai();
        pegawai = new PegawaiModel();
        users = new UsersModel();
        mobil = new MobilModel();
        peminjaman = new PeminjamanModel();
        initComponents();        
        
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        greetingsText = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idPegawaiField = new javax.swing.JTextField();
        namaField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatField = new javax.swing.JTextArea();
        insertButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        searchPegawaiField = new javax.swing.JTextField();
        searchPegawaiButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        dataPegawaiTable = new javax.swing.JTable();
        refreshPegawaiButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        editIdPegawaiField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        editNamaPegawaiField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        editContactPegawaiField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        editAlamatPegawaiField = new javax.swing.JTextArea();
        editUsernamePegawaiField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        editPegawaiButton = new javax.swing.JButton();
        cancelPegawaiButton = new javax.swing.JButton();
        deletePegawaiButton = new javax.swing.JButton();
        editPasswordPegawaiField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        idMobilField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jenisMobilField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        sewaMobilField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        stokMobilField = new javax.swing.JTextField();
        insertMobilButton = new javax.swing.JButton();
        resetMobilButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        searchMobilField = new javax.swing.JTextField();
        searchMobilButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        dataMobilTable = new javax.swing.JTable();
        refreshMobilButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        editIdMobilField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        editJenisMobilField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        editSewaMobilField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        editStokMobilField = new javax.swing.JTextField();
        editMobilButton = new javax.swing.JButton();
        cancelMobilButton = new javax.swing.JButton();
        deleteMobilButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greetingsText.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        greetingsText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        greetingsText.setText("Hello, ");
        jPanel2.add(greetingsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 43, -1, -1));

        logOutButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 401, 149, 75));

        jTabbedPane1.addTab("Admin", jPanel2);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setText("Insert Data Pegawai");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Username");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(usernameField)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Id Pegawai (Contoh : 100)");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("Alamat");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Contact");

        alamatField.setColumns(20);
        alamatField.setRows(5);
        jScrollPane1.setViewportView(alamatField);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(contactField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idPegawaiField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Input Pegawai", jPanel3);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel9.setText("DATA PEGAWAI");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setText("Id Pegawai ");

        searchPegawaiButton.setText("Search");
        searchPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPegawaiButtonActionPerformed(evt);
            }
        });

        dataPegawaiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Contact", "Username", "Password", "Kode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataPegawaiTable.setFocusable(false);
        dataPegawaiTable.setVerifyInputWhenFocusTarget(false);
        dataPegawaiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPegawaiTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(dataPegawaiTable);

        refreshPegawaiButton.setText("Refresh");
        refreshPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPegawaiButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setText("Id Pegawai ");

        editIdPegawaiField.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Nama");

        editNamaPegawaiField.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("Alamat");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel14.setText("Contact");

        editContactPegawaiField.setEnabled(false);

        editAlamatPegawaiField.setColumns(20);
        editAlamatPegawaiField.setRows(5);
        editAlamatPegawaiField.setEnabled(false);
        jScrollPane2.setViewportView(editAlamatPegawaiField);

        editUsernamePegawaiField.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel15.setText("Username");

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel16.setText("Password");

        editPegawaiButton.setText("Edit");
        editPegawaiButton.setEnabled(false);
        editPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPegawaiButtonActionPerformed(evt);
            }
        });

        cancelPegawaiButton.setText("Cancel");
        cancelPegawaiButton.setEnabled(false);
        cancelPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPegawaiButtonActionPerformed(evt);
            }
        });

        deletePegawaiButton.setText("Delete");
        deletePegawaiButton.setEnabled(false);
        deletePegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePegawaiButtonActionPerformed(evt);
            }
        });

        editPasswordPegawaiField.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel9))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(searchPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(refreshPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(editIdPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editUsernamePegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editContactPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)
                                .addComponent(editNamaPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editPasswordPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(editPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deletePegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(searchPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel11))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(editIdPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel12))
                            .addComponent(editNamaPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editContactPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editUsernamePegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(editPasswordPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletePegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Pegawai", jPanel6);

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel19.setText("Insert Data Mobil");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel20.setText("Id Mobil (Contoh : ER3)");

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel21.setText("Jenis");

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel22.setText("Sewa (/hari)");

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel23.setText("Stok");

        insertMobilButton.setText("Insert");
        insertMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertMobilButtonActionPerformed(evt);
            }
        });

        resetMobilButton.setText("Reset");
        resetMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMobilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(sewaMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(stokMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jenisMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(insertMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(resetMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(284, 284, 284))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sewaMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stokMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Input Mobil", jPanel7);

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel25.setText("DATA MOBIL");

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel26.setText("Id Mobil");

        searchMobilButton.setText("Search");
        searchMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMobilButtonActionPerformed(evt);
            }
        });

        dataMobilTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Jenis", "Sewa (/hari)", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataMobilTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMobilTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataMobilTableMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(dataMobilTable);

        refreshMobilButton.setText("Refresh");
        refreshMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshMobilButtonActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel24.setText("Id Mobil");

        editIdMobilField.setEnabled(false);

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel27.setText("Jenis");

        editJenisMobilField.setEnabled(false);

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel28.setText("Sewa");

        editSewaMobilField.setEnabled(false);

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel29.setText("Stok");

        editStokMobilField.setEnabled(false);

        editMobilButton.setText("Edit");
        editMobilButton.setEnabled(false);
        editMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMobilButtonActionPerformed(evt);
            }
        });

        cancelMobilButton.setText("Cancel");
        cancelMobilButton.setEnabled(false);
        cancelMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMobilButtonActionPerformed(evt);
            }
        });

        deleteMobilButton.setText("Delete");
        deleteMobilButton.setEnabled(false);
        deleteMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMobilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editSewaMobilField, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(editIdMobilField)
                                    .addComponent(editJenisMobilField)
                                    .addComponent(editStokMobilField)))
                            .addComponent(deleteMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(editMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(132, Short.MAX_VALUE)
                        .addComponent(cancelMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(335, 335, 335))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(searchMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(editIdMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(editJenisMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editSewaMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(editStokMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cancelMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Data Mobil", jPanel8);

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Pelanggan", "Mobil", "Pegawai", "Tanggal Pinjam", "Tanggal Kembali", "Sewa", "Denda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reportTable.setToolTipText("");
        jScrollPane3.setViewportView(reportTable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Report", jPanel9);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("MOMOBILAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(284, 284, 284))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        LoginForm form = new LoginForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void insertMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertMobilButtonActionPerformed
        // TODO add your handling code here:
        String idMobil = idMobilField.getText();
        String jenis = jenisMobilField.getText();
        String sewa = sewaMobilField.getText();
        String stok = stokMobilField.getText();
        
        if (mobil.insert(idMobil, jenis, sewa, stok))        
        {
            JOptionPane.showMessageDialog(rootPane, "Insert Data Berhasil", "Success", 1);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Insert Data Gagal", "Error", 2);
        }
        
        tampilkan();
        idMobilField.setText("");
        jenisMobilField.setText("");
        sewaMobilField.setText("");
        stokMobilField.setText("");
    }//GEN-LAST:event_insertMobilButtonActionPerformed

    private void resetMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMobilButtonActionPerformed
        // TODO add your handling code here:
        idMobilField.setText("");
        jenisMobilField.setText("");
        sewaMobilField.setText("");
        stokMobilField.setText("");
        
        idMobilField.requestFocus();
    }//GEN-LAST:event_resetMobilButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        idPegawaiField.setText("");
        namaField.setText("");
        alamatField.setText("");
        contactField.setText("");
        usernameField.setText("");
        passwordField.setText("");
        
        idPegawaiField.requestFocus();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        String idPegawai = idPegawaiField.getText();
        String nama = namaField.getText();
        String alamat = alamatField.getText();
        String contact = contactField.getText();
        String username = usernameField.getText();
        String password = passwordField.getText();
        
        if (pegawai.insert(idPegawai, nama, alamat, contact))
        {
            if (users.insert(username, password, idPegawai))
            {
                JOptionPane.showMessageDialog(rootPane, "Insert Data Berhasil", "Success", 1);
            }                
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Insert Data Gagal", "Error", 2);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Insert Data Gagal", "Error", 2);
        }
        
        idPegawaiField.setText("");
        namaField.setText("");
        alamatField.setText("");
        contactField.setText("");
        usernameField.setText("");
        passwordField.setText("");
        
        tampilkan();
    }//GEN-LAST:event_insertButtonActionPerformed

    private void refreshMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshMobilButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < dataMobilTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataMobilTable.getColumnCount(); j++)
            {
                dataMobilTable.setValueAt("", i, j);
            }
        }
        
        tampilkan();
    }//GEN-LAST:event_refreshMobilButtonActionPerformed

    private void refreshPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPegawaiButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < dataPegawaiTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPegawaiTable.getColumnCount(); j++)
            {
                dataPegawaiTable.setValueAt("", i, j);
            }
        }
        
        tampilkan();
    }//GEN-LAST:event_refreshPegawaiButtonActionPerformed

    private void searchMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMobilButtonActionPerformed
        for (int i = 0; i < dataMobilTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataMobilTable.getColumnCount(); j++)
            {
                dataMobilTable.setValueAt("", i, j);
            }
        }
        
        try {            
            ResultSet hasil = mobil.searchData(searchMobilField.getText());
            while (hasil.next())
            {
                dataMobilTable.setValueAt(hasil.getString(1), 0, 0);
                dataMobilTable.setValueAt(hasil.getString(2), 0, 1);
                dataMobilTable.setValueAt(hasil.getString(3), 0, 2);
                dataMobilTable.setValueAt(hasil.getString(4), 0, 3);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchMobilButtonActionPerformed

    private void searchPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPegawaiButtonActionPerformed
        for (int i = 0; i < dataPegawaiTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPegawaiTable.getColumnCount(); j++)
            {
                dataPegawaiTable.setValueAt("", i, j);
            }
        }
        
        try {            
            ResultSet hasilPegawai = pegawai.searchData(searchPegawaiField.getText());
            ResultSet hasilUsers = users.searchData(searchPegawaiField.getText());
            while (hasilPegawai.next())
            {
                dataPegawaiTable.setValueAt(hasilPegawai.getString(1), 0, 0);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(2), 0, 1);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(3), 0, 2);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(4), 0, 3);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(5), 0, 4);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(6), 0, 5);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(8), 0, 6);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchPegawaiButtonActionPerformed

    private void editPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPegawaiButtonActionPerformed
        // TODO add your handling code here:
        String id = editIdPegawaiField.getText();
        String nama = editNamaPegawaiField.getText();
        String alamat = editAlamatPegawaiField.getText();
        String contact = editContactPegawaiField.getText();
        String username = editUsernamePegawaiField.getText();
        String password = editPasswordPegawaiField.getText();
        
        pegawai.update(id, nama, alamat, contact);
        users.update(id, username, password);
        
        editIdPegawaiField.setText("");
        editNamaPegawaiField.setText("");
        editAlamatPegawaiField.setText("");
        editContactPegawaiField.setText("");
        editUsernamePegawaiField.setText("");
        editPasswordPegawaiField.setText("");

        editNamaPegawaiField.setEnabled(false);
        editAlamatPegawaiField.setEnabled(false);
        editContactPegawaiField.setEnabled(false);
        editUsernamePegawaiField.setEnabled(false);
        editPasswordPegawaiField.setEnabled(false);

        editPegawaiButton.setEnabled(false);
        deletePegawaiButton.setEnabled(false);
        cancelPegawaiButton.setEnabled(false);
        tampilkan();
    }//GEN-LAST:event_editPegawaiButtonActionPerformed

    private void cancelPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPegawaiButtonActionPerformed
        // TODO add your handling code here:
        editIdPegawaiField.setText("");
        editNamaPegawaiField.setText("");
        editAlamatPegawaiField.setText("");
        editContactPegawaiField.setText("");
        editUsernamePegawaiField.setText("");
        editPasswordPegawaiField.setText("");

        editNamaPegawaiField.setEnabled(false);
        editAlamatPegawaiField.setEnabled(false);
        editContactPegawaiField.setEnabled(false);
        editUsernamePegawaiField.setEnabled(false);
        editPasswordPegawaiField.setEnabled(false);

        editPegawaiButton.setEnabled(false);
        deletePegawaiButton.setEnabled(false);
        cancelPegawaiButton.setEnabled(false);
    }//GEN-LAST:event_cancelPegawaiButtonActionPerformed

    private void editMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMobilButtonActionPerformed
        // TODO add your handling code here:   
        String id = editIdMobilField.getText();
        String jenis = editJenisMobilField.getText();
        String sewa = editSewaMobilField.getText();
        String stok = editStokMobilField.getText();
        
        mobil.update(id, jenis, sewa, stok);
        
        editIdMobilField.setText("");
        editJenisMobilField.setText("");
        editSewaMobilField.setText("");                
        editStokMobilField.setText("");                
        
        editJenisMobilField.setEnabled(false);
        editSewaMobilField.setEnabled(false);
        editStokMobilField.setEnabled(false);                

        editMobilButton.setEnabled(false);
        deleteMobilButton.setEnabled(false);
        cancelMobilButton.setEnabled(false);
        tampilkan();
    }//GEN-LAST:event_editMobilButtonActionPerformed

    private void cancelMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMobilButtonActionPerformed
        // TODO add your handling code here:
        editIdMobilField.setText("");
        editJenisMobilField.setText("");
        editSewaMobilField.setText("");                
        editStokMobilField.setText("");                
        
        editJenisMobilField.setEnabled(false);
        editSewaMobilField.setEnabled(false);
        editStokMobilField.setEnabled(false);                

        editMobilButton.setEnabled(false);
        deleteMobilButton.setEnabled(false);
        cancelMobilButton.setEnabled(false);
    }//GEN-LAST:event_cancelMobilButtonActionPerformed

    private void dataMobilTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMobilTableMouseClicked
        // TODO add your handling code here:
        try 
        {
            if (evt.getClickCount() == 2)
            {
                int row = dataMobilTable.getSelectedRow();
                editIdMobilField.setText(dataMobilTable.getValueAt(row, 0).toString());
                editJenisMobilField.setText(dataMobilTable.getValueAt(row, 1).toString());
                editSewaMobilField.setText(dataMobilTable.getValueAt(row, 2).toString());                
                editStokMobilField.setText(dataMobilTable.getValueAt(row, 3).toString());                
                
                editJenisMobilField.setEnabled(true);
                editSewaMobilField.setEnabled(true);
                editStokMobilField.setEnabled(true);                

                editMobilButton.setEnabled(true);
                deleteMobilButton.setEnabled(true);
                cancelMobilButton.setEnabled(true);
            }
        }
        catch (Throwable t)
        {
            JOptionPane.showMessageDialog(rootPane, "Data Kosong!", "Error", 2);
        } 
    }//GEN-LAST:event_dataMobilTableMouseClicked

    private void dataPegawaiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPegawaiTableMouseClicked
        // TODO add your handling code here:
        try 
        {
            if (evt.getClickCount() == 2)
            {
                int row = dataPegawaiTable.getSelectedRow();
                editIdPegawaiField.setText(dataPegawaiTable.getValueAt(row, 0).toString());
                editNamaPegawaiField.setText(dataPegawaiTable.getValueAt(row, 1).toString());
                editAlamatPegawaiField.setText(dataPegawaiTable.getValueAt(row, 2).toString());
                editContactPegawaiField.setText(dataPegawaiTable.getValueAt(row, 3).toString());
                editUsernamePegawaiField.setText(dataPegawaiTable.getValueAt(row, 4).toString());
                editPasswordPegawaiField.setText(dataPegawaiTable.getValueAt(row, 5).toString());

                editNamaPegawaiField.setEnabled(true);
                editAlamatPegawaiField.setEnabled(true);
                editContactPegawaiField.setEnabled(true);
                editUsernamePegawaiField.setEnabled(true);
                editPasswordPegawaiField.setEnabled(true);

                editPegawaiButton.setEnabled(true);
                deletePegawaiButton.setEnabled(true);
                cancelPegawaiButton.setEnabled(true);
            }
        }
        catch (Throwable t)
        {
            JOptionPane.showMessageDialog(rootPane, "Data Kosong!", "Error", 2);
        }        
    }//GEN-LAST:event_dataPegawaiTableMouseClicked

    private void deletePegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePegawaiButtonActionPerformed
        // TODO add your handling code here:
        String id = editIdPegawaiField.getText();
        
        users.delete(id);
        pegawai.delete(id);
        
        editIdPegawaiField.setText("");
        editNamaPegawaiField.setText("");
        editAlamatPegawaiField.setText("");
        editContactPegawaiField.setText("");
        editUsernamePegawaiField.setText("");
        editPasswordPegawaiField.setText("");

        editNamaPegawaiField.setEnabled(false);
        editAlamatPegawaiField.setEnabled(false);
        editContactPegawaiField.setEnabled(false);
        editUsernamePegawaiField.setEnabled(false);
        editPasswordPegawaiField.setEnabled(false);

        editPegawaiButton.setEnabled(false);
        deletePegawaiButton.setEnabled(false);
        cancelPegawaiButton.setEnabled(false);
        tampilkan();
    }//GEN-LAST:event_deletePegawaiButtonActionPerformed

    private void dataMobilTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMobilTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dataMobilTableMouseEntered

    private void deleteMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMobilButtonActionPerformed
        // TODO add your handling code here:
        mobil.delete(editIdMobilField.getText());
        editIdMobilField.setText("");
        editJenisMobilField.setText("");
        editSewaMobilField.setText("");                
        editStokMobilField.setText("");                
        
        editJenisMobilField.setEnabled(false);
        editSewaMobilField.setEnabled(false);
        editStokMobilField.setEnabled(false);                

        editMobilButton.setEnabled(false);
        deleteMobilButton.setEnabled(false);
        cancelMobilButton.setEnabled(false);
        tampilkan();
    }//GEN-LAST:event_deleteMobilButtonActionPerformed

    private void startup()
    {
        try {
            ResultSet hasil = pegawai.searchData(id);
            while (hasil.next())
            {
                data.setId(hasil.getString(1));
                data.setNama(hasil.getString(2));
                data.setAlamat(hasil.getString(3));
                data.setContact(hasil.getString(4));
            }                        
            
            greetingsText.setText("Hello, " + data.getNama());
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tampilkan()
    {
        for (int i = 0; i < dataPegawaiTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPegawaiTable.getColumnCount(); j++)
            {
                dataPegawaiTable.setValueAt("", i, j);
            }
        }
        
        for (int i = 0; i < dataMobilTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataMobilTable.getColumnCount(); j++)
            {
                dataMobilTable.setValueAt("", i, j);
            }
        }
        
        for (int i = 0; i < reportTable.getRowCount(); i++)
        {
            for (int j = 0; j < reportTable.getColumnCount(); j++)
            {
                reportTable.setValueAt("", i, j);
            }
        }
        
        try {
            ResultSet hasilPegawai = pegawai.getData();
            ResultSet hasilUsers = users.getData();
            
            int row = 0;
            while (hasilPegawai.next() && hasilUsers.next())
            {
                dataPegawaiTable.setValueAt(hasilPegawai.getString(1), row, 0);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(2), row, 1);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(3), row, 2);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(4), row, 3);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(5), row, 4);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(6), row, 5);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(8), row, 6);                
                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        try {
            ResultSet hasilMobil = mobil.getData();
        
            int row = 0;
            while (hasilMobil.next())
            {
                dataMobilTable.setValueAt(hasilMobil.getString(1), row, 0);
                dataMobilTable.setValueAt(hasilMobil.getString(2), row, 1);
                dataMobilTable.setValueAt(hasilMobil.getString(3), row, 2);
                dataMobilTable.setValueAt(hasilMobil.getString(4), row, 3);
                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            ResultSet hasilPeminjaman = peminjaman.getData();
        
            int row = 0;
            while (hasilPeminjaman.next())
            {
                reportTable.setValueAt(hasilPeminjaman.getString(1), row, 0);
                reportTable.setValueAt(hasilPeminjaman.getString(3), row, 1);
                reportTable.setValueAt(hasilPeminjaman.getString(4), row, 2);
                reportTable.setValueAt(hasilPeminjaman.getString(2), row, 3);
                reportTable.setValueAt(hasilPeminjaman.getString(5), row, 4);
                reportTable.setValueAt(hasilPeminjaman.getString(6), row, 5);
                reportTable.setValueAt(hasilPeminjaman.getString(9), row, 6);
                reportTable.setValueAt(hasilPeminjaman.getString(10), row, 7);
                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatField;
    private javax.swing.JButton cancelMobilButton;
    private javax.swing.JButton cancelPegawaiButton;
    private javax.swing.JTextField contactField;
    private javax.swing.JTable dataMobilTable;
    private javax.swing.JTable dataPegawaiTable;
    private javax.swing.JButton deleteMobilButton;
    private javax.swing.JButton deletePegawaiButton;
    private javax.swing.JTextArea editAlamatPegawaiField;
    private javax.swing.JTextField editContactPegawaiField;
    private javax.swing.JTextField editIdMobilField;
    private javax.swing.JTextField editIdPegawaiField;
    private javax.swing.JTextField editJenisMobilField;
    private javax.swing.JButton editMobilButton;
    private javax.swing.JTextField editNamaPegawaiField;
    private javax.swing.JTextField editPasswordPegawaiField;
    private javax.swing.JButton editPegawaiButton;
    private javax.swing.JTextField editSewaMobilField;
    private javax.swing.JTextField editStokMobilField;
    private javax.swing.JTextField editUsernamePegawaiField;
    private javax.swing.JLabel greetingsText;
    private javax.swing.JTextField idMobilField;
    private javax.swing.JTextField idPegawaiField;
    private javax.swing.JButton insertButton;
    private javax.swing.JButton insertMobilButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jenisMobilField;
    private javax.swing.JButton logOutButton;
    private javax.swing.JTextField namaField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton refreshMobilButton;
    private javax.swing.JButton refreshPegawaiButton;
    private javax.swing.JTable reportTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetMobilButton;
    private javax.swing.JButton searchMobilButton;
    private javax.swing.JTextField searchMobilField;
    private javax.swing.JButton searchPegawaiButton;
    private javax.swing.JTextField searchPegawaiField;
    private javax.swing.JTextField sewaMobilField;
    private javax.swing.JTextField stokMobilField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
