/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentalmobil;
import rentalmobil.Package.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nurka
 */
public class AdminPage extends javax.swing.JFrame {
    
    private Pegawai data;
    private PegawaiModel pegawai;
    private UsersModel users;
    private MobilModel mobil;
    private PeminjamanModel peminjaman;
    private String id;

    public void setId(String id) 
    {
        this.id = id;
        
        startup();
    }
       
    /**
     * Creates new form AdminPage
     */
    public AdminPage() {      
        data = new Pegawai();
        pegawai = new PegawaiModel();
        users = new UsersModel();
        mobil = new MobilModel();
        peminjaman = new PeminjamanModel();
        this.id = "";
        initComponents();        
        
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        greetingsText = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idPegawaiField = new javax.swing.JTextField();
        namaField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatField = new javax.swing.JTextArea();
        insertButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        searchPegawaiField = new javax.swing.JTextField();
        searchPegawaiButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        dataPegawaiTable = new javax.swing.JTable();
        refreshPegawaiButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        editIdPegawaiField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        editNamaPegawaiField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        editContactPegawaiField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        editAlamatPegawaiField = new javax.swing.JTextArea();
        editUsernamePegawaiField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        editPegawaiButton = new javax.swing.JButton();
        cancelPegawaiButton = new javax.swing.JButton();
        deletePegawaiButton = new javax.swing.JButton();
        editPasswordPegawaiField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        idMobilField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jenisMobilField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        sewaMobilField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        stokMobilField = new javax.swing.JTextField();
        insertMobilButton = new javax.swing.JButton();
        resetMobilButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        searchMobilField = new javax.swing.JTextField();
        searchMobilButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        dataMobilTable = new javax.swing.JTable();
        refreshMobilButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        editIdMobilField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        editJenisMobilField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        editSewaMobilField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        editStokMobilField = new javax.swing.JTextField();
        editMobilButton = new javax.swing.JButton();
        cancelMobilButton = new javax.swing.JButton();
        deleteMobilButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setResizable(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greetingsText.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        greetingsText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        greetingsText.setText("Hello, ");
        jPanel2.add(greetingsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        logOutButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 401, 149, 75));

        jTabbedPane1.addTab("Admin", jPanel2);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setText("Insert Data Pegawai");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Username");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(usernameField)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Id Pegawai (Contoh : 100)");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("Alamat");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Contact");

        alamatField.setColumns(20);
        alamatField.setRows(5);
        jScrollPane1.setViewportView(alamatField);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(contactField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idPegawaiField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Input Pegawai", jPanel3);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel9.setText("DATA PEGAWAI");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 6, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setText("Nama Pegawai");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        searchPegawaiField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchPegawaiFieldKeyPressed(evt);
            }
        });
        jPanel6.add(searchPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 55, 189, 30));

        searchPegawaiButton.setText("Search");
        searchPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPegawaiButtonActionPerformed(evt);
            }
        });
        jPanel6.add(searchPegawaiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 56, 100, 30));

        dataPegawaiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Contact", "Username", "Password", "Kode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataPegawaiTable.setFocusable(false);
        dataPegawaiTable.setVerifyInputWhenFocusTarget(false);
        dataPegawaiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPegawaiTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(dataPegawaiTable);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 98, 534, 392));

        refreshPegawaiButton.setText("Refresh");
        refreshPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPegawaiButtonActionPerformed(evt);
            }
        });
        jPanel6.add(refreshPegawaiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 56, 100, 30));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setText("Id Pegawai ");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 107, -1, -1));

        editIdPegawaiField.setEnabled(false);
        jPanel6.add(editIdPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 106, 240, 30));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Nama");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 149, -1, -1));

        editNamaPegawaiField.setEnabled(false);
        jPanel6.add(editNamaPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 148, 240, 30));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("Alamat");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel14.setText("Contact");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 295, -1, -1));

        editContactPegawaiField.setEnabled(false);
        jPanel6.add(editContactPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 294, 243, 30));

        editAlamatPegawaiField.setColumns(20);
        editAlamatPegawaiField.setRows(5);
        editAlamatPegawaiField.setEnabled(false);
        jScrollPane2.setViewportView(editAlamatPegawaiField);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 190, 240, -1));

        editUsernamePegawaiField.setEnabled(false);
        jPanel6.add(editUsernamePegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 336, 243, 30));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel15.setText("Username");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 337, -1, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel16.setText("Password");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 378, -1, -1));

        editPegawaiButton.setText("Edit");
        editPegawaiButton.setEnabled(false);
        editPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPegawaiButtonActionPerformed(evt);
            }
        });
        jPanel6.add(editPegawaiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 426, 100, 30));

        cancelPegawaiButton.setText("Cancel");
        cancelPegawaiButton.setEnabled(false);
        cancelPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPegawaiButtonActionPerformed(evt);
            }
        });
        jPanel6.add(cancelPegawaiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 426, 100, 30));

        deletePegawaiButton.setText("Delete");
        deletePegawaiButton.setEnabled(false);
        deletePegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePegawaiButtonActionPerformed(evt);
            }
        });
        jPanel6.add(deletePegawaiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 426, 100, 30));

        editPasswordPegawaiField.setEnabled(false);
        jPanel6.add(editPasswordPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 378, 243, 30));

        jTabbedPane1.addTab("Data Pegawai", jPanel6);

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel19.setText("Insert Data Mobil");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel20.setText("Id Mobil (Contoh : ER3)");

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel21.setText("Jenis");

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel22.setText("Sewa (/hari)");

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel23.setText("Stok");

        insertMobilButton.setText("Insert");
        insertMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertMobilButtonActionPerformed(evt);
            }
        });

        resetMobilButton.setText("Reset");
        resetMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMobilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(sewaMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(stokMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jenisMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(insertMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(resetMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(284, 284, 284))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sewaMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stokMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Input Mobil", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel25.setText("DATA MOBIL");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 8, -1, -1));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel26.setText("Jenis Mobil");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, 30));

        searchMobilField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchMobilFieldKeyPressed(evt);
            }
        });
        jPanel8.add(searchMobilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 59, 201, 30));

        searchMobilButton.setText("Search");
        searchMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMobilButtonActionPerformed(evt);
            }
        });
        jPanel8.add(searchMobilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 60, 100, 30));

        dataMobilTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Jenis", "Sewa (/hari)", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataMobilTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMobilTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataMobilTableMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(dataMobilTable);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 102, 593, 380));

        refreshMobilButton.setText("Refresh");
        refreshMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshMobilButtonActionPerformed(evt);
            }
        });
        jPanel8.add(refreshMobilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 60, 100, 30));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel24.setText("Id Mobil");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 112, -1, -1));

        editIdMobilField.setEnabled(false);
        jPanel8.add(editIdMobilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 111, 218, 30));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel27.setText("Jenis");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 160, -1, -1));

        editJenisMobilField.setEnabled(false);
        jPanel8.add(editJenisMobilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 159, 218, 30));

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel28.setText("Sewa");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 202, -1, -1));

        editSewaMobilField.setEnabled(false);
        jPanel8.add(editSewaMobilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 201, 218, 30));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel29.setText("Stok");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 244, -1, -1));

        editStokMobilField.setEnabled(false);
        jPanel8.add(editStokMobilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 243, 218, 30));

        editMobilButton.setText("Edit");
        editMobilButton.setEnabled(false);
        editMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMobilButtonActionPerformed(evt);
            }
        });
        jPanel8.add(editMobilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 291, 100, 30));

        cancelMobilButton.setText("Cancel");
        cancelMobilButton.setEnabled(false);
        cancelMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMobilButtonActionPerformed(evt);
            }
        });
        jPanel8.add(cancelMobilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 339, 100, 30));

        deleteMobilButton.setText("Delete");
        deleteMobilButton.setEnabled(false);
        deleteMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMobilButtonActionPerformed(evt);
            }
        });
        jPanel8.add(deleteMobilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 291, 100, 30));

        jTabbedPane1.addTab("Data Mobil", jPanel8);

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Pelanggan", "Mobil", "Pegawai", "Tanggal Pinjam", "Tanggal Kembali", "Sewa", "Denda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reportTable.setToolTipText("");
        jScrollPane3.setViewportView(reportTable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Report", jPanel9);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("MOMOBILAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(284, 284, 284))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        LoginForm form = new LoginForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void insertMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertMobilButtonActionPerformed
        // TODO add your handling code here:
        String idMobil = idMobilField.getText();
        String jenis = jenisMobilField.getText();
        String sewa = sewaMobilField.getText();
        String stok = stokMobilField.getText();
        
        if (mobil.insert(idMobil, jenis, sewa, stok))        
        {
            JOptionPane.showMessageDialog(rootPane, "Insert Data Berhasil", "Success", 1);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Insert Data Gagal", "Error", 2);
        }
        
        tampilkan();
        idMobilField.setText("");
        jenisMobilField.setText("");
        sewaMobilField.setText("");
        stokMobilField.setText("");
    }//GEN-LAST:event_insertMobilButtonActionPerformed

    private void resetMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMobilButtonActionPerformed
        // TODO add your handling code here:
        idMobilField.setText("");
        jenisMobilField.setText("");
        sewaMobilField.setText("");
        stokMobilField.setText("");
        
        idMobilField.requestFocus();
    }//GEN-LAST:event_resetMobilButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        idPegawaiField.setText("");
        namaField.setText("");
        alamatField.setText("");
        contactField.setText("");
        usernameField.setText("");
        passwordField.setText("");
        
        idPegawaiField.requestFocus();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        String idPegawai = idPegawaiField.getText();
        String nama = namaField.getText();
        String alamat = alamatField.getText();
        String contact = contactField.getText();
        String username = usernameField.getText();
        String password = passwordField.getText();
        
        if (pegawai.insert(idPegawai, nama, alamat, contact))
        {
            if (users.insert(username, password, idPegawai))
            {
                JOptionPane.showMessageDialog(rootPane, "Insert Data Berhasil", "Success", 1);
            }                
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Insert Data Gagal", "Error", 2);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Insert Data Gagal", "Error", 2);
        }
        
        idPegawaiField.setText("");
        namaField.setText("");
        alamatField.setText("");
        contactField.setText("");
        usernameField.setText("");
        passwordField.setText("");
        
        tampilkan();
    }//GEN-LAST:event_insertButtonActionPerformed

    private void refreshMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshMobilButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < dataMobilTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataMobilTable.getColumnCount(); j++)
            {
                dataMobilTable.setValueAt("", i, j);
            }
        }
        
        tampilkan();
    }//GEN-LAST:event_refreshMobilButtonActionPerformed

    private void refreshPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPegawaiButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < dataPegawaiTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPegawaiTable.getColumnCount(); j++)
            {
                dataPegawaiTable.setValueAt("", i, j);
            }
        }
        
        tampilkan();
    }//GEN-LAST:event_refreshPegawaiButtonActionPerformed

    private void searchMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMobilButtonActionPerformed
        for (int i = 0; i < dataMobilTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataMobilTable.getColumnCount(); j++)
            {
                dataMobilTable.setValueAt("", i, j);
            }
        }
        
        try {            
            ResultSet hasil = mobil.searchData(searchMobilField.getText());
            while (hasil.next())
            {
                dataMobilTable.setValueAt(hasil.getString(1), 0, 0);
                dataMobilTable.setValueAt(hasil.getString(2), 0, 1);
                dataMobilTable.setValueAt(hasil.getString(3), 0, 2);
                dataMobilTable.setValueAt(hasil.getString(4), 0, 3);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchMobilButtonActionPerformed

    private void searchPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPegawaiButtonActionPerformed
        for (int i = 0; i < dataPegawaiTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPegawaiTable.getColumnCount(); j++)
            {
                dataPegawaiTable.setValueAt("", i, j);
            }
        }
        
        try {            
            ResultSet hasilPegawai = pegawai.searchData(searchPegawaiField.getText());            
            while (hasilPegawai.next())
            {
                dataPegawaiTable.setValueAt(hasilPegawai.getString(1), 0, 0);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(2), 0, 1);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(3), 0, 2);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(4), 0, 3);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(5), 0, 4);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(6), 0, 5);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(8), 0, 6);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchPegawaiButtonActionPerformed

    private void editPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPegawaiButtonActionPerformed
        // TODO add your handling code here:
        String id = editIdPegawaiField.getText();
        String nama = editNamaPegawaiField.getText();
        String alamat = editAlamatPegawaiField.getText();
        String contact = editContactPegawaiField.getText();
        String username = editUsernamePegawaiField.getText();
        String password = editPasswordPegawaiField.getText();
        
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Apakah Kamu Yakin?", "Update", 1);
        
        if (opsi == 0)
        {
            pegawai.update(id, nama, alamat, contact);
            users.update(id, username, password);
            JOptionPane.showMessageDialog(rootPane, "Update Data Berhasil!", "Success", 1);

            editIdPegawaiField.setText("");
            editNamaPegawaiField.setText("");
            editAlamatPegawaiField.setText("");
            editContactPegawaiField.setText("");
            editUsernamePegawaiField.setText("");
            editPasswordPegawaiField.setText("");

            editNamaPegawaiField.setEnabled(false);
            editAlamatPegawaiField.setEnabled(false);
            editContactPegawaiField.setEnabled(false);
            editUsernamePegawaiField.setEnabled(false);
            editPasswordPegawaiField.setEnabled(false);

            editPegawaiButton.setEnabled(false);
            deletePegawaiButton.setEnabled(false);
            cancelPegawaiButton.setEnabled(false);
            tampilkan();
        }                
    }//GEN-LAST:event_editPegawaiButtonActionPerformed

    private void cancelPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPegawaiButtonActionPerformed
        // TODO add your handling code here:
        editIdPegawaiField.setText("");
        editNamaPegawaiField.setText("");
        editAlamatPegawaiField.setText("");
        editContactPegawaiField.setText("");
        editUsernamePegawaiField.setText("");
        editPasswordPegawaiField.setText("");

        editNamaPegawaiField.setEnabled(false);
        editAlamatPegawaiField.setEnabled(false);
        editContactPegawaiField.setEnabled(false);
        editUsernamePegawaiField.setEnabled(false);
        editPasswordPegawaiField.setEnabled(false);

        editPegawaiButton.setEnabled(false);
        deletePegawaiButton.setEnabled(false);
        cancelPegawaiButton.setEnabled(false);
    }//GEN-LAST:event_cancelPegawaiButtonActionPerformed

    private void editMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMobilButtonActionPerformed
        // TODO add your handling code here:   
        String id = editIdMobilField.getText();
        String jenis = editJenisMobilField.getText();
        String sewa = editSewaMobilField.getText();
        String stok = editStokMobilField.getText();
        
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Apakah Kamu Yakin?", "Update", 1);
        
        if (opsi == 0)
        {
            mobil.update(id, jenis, sewa, stok);
            JOptionPane.showMessageDialog(rootPane, "Update Data Berhasil!", "Success", 1);

            editIdMobilField.setText("");
            editJenisMobilField.setText("");
            editSewaMobilField.setText("");                
            editStokMobilField.setText("");                

            editJenisMobilField.setEnabled(false);
            editSewaMobilField.setEnabled(false);
            editStokMobilField.setEnabled(false);                

            editMobilButton.setEnabled(false);
            deleteMobilButton.setEnabled(false);
            cancelMobilButton.setEnabled(false);
            tampilkan();
        }                
    }//GEN-LAST:event_editMobilButtonActionPerformed

    private void cancelMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMobilButtonActionPerformed
        // TODO add your handling code here:
        editIdMobilField.setText("");
        editJenisMobilField.setText("");
        editSewaMobilField.setText("");                
        editStokMobilField.setText("");                
        
        editJenisMobilField.setEnabled(false);
        editSewaMobilField.setEnabled(false);
        editStokMobilField.setEnabled(false);                

        editMobilButton.setEnabled(false);
        deleteMobilButton.setEnabled(false);
        cancelMobilButton.setEnabled(false);
    }//GEN-LAST:event_cancelMobilButtonActionPerformed

    private void dataMobilTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMobilTableMouseClicked
        // TODO add your handling code here:
        try 
        {
            if (evt.getClickCount() == 2)
            {
                int row = dataMobilTable.getSelectedRow();
                editIdMobilField.setText(dataMobilTable.getValueAt(row, 0).toString());
                editJenisMobilField.setText(dataMobilTable.getValueAt(row, 1).toString());
                editSewaMobilField.setText(dataMobilTable.getValueAt(row, 2).toString());                
                editStokMobilField.setText(dataMobilTable.getValueAt(row, 3).toString());                
                
                editJenisMobilField.setEnabled(true);
                editSewaMobilField.setEnabled(true);
                editStokMobilField.setEnabled(true);                

                editMobilButton.setEnabled(true);
                deleteMobilButton.setEnabled(true);
                cancelMobilButton.setEnabled(true);
            }
        }
        catch (Throwable t)
        {
            JOptionPane.showMessageDialog(rootPane, "Data Kosong!", "Error", 2);
        } 
    }//GEN-LAST:event_dataMobilTableMouseClicked

    private void dataPegawaiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPegawaiTableMouseClicked
        // TODO add your handling code here:
        try 
        {
            if (evt.getClickCount() == 2)
            {
                int row = dataPegawaiTable.getSelectedRow();
                editIdPegawaiField.setText(dataPegawaiTable.getValueAt(row, 0).toString());
                editNamaPegawaiField.setText(dataPegawaiTable.getValueAt(row, 1).toString());
                editAlamatPegawaiField.setText(dataPegawaiTable.getValueAt(row, 2).toString());
                editContactPegawaiField.setText(dataPegawaiTable.getValueAt(row, 3).toString());
                editUsernamePegawaiField.setText(dataPegawaiTable.getValueAt(row, 4).toString());
                editPasswordPegawaiField.setText(dataPegawaiTable.getValueAt(row, 5).toString());

                editNamaPegawaiField.setEnabled(true);
                editAlamatPegawaiField.setEnabled(true);
                editContactPegawaiField.setEnabled(true);
                editUsernamePegawaiField.setEnabled(true);
                editPasswordPegawaiField.setEnabled(true);

                editPegawaiButton.setEnabled(true);
                deletePegawaiButton.setEnabled(true);
                cancelPegawaiButton.setEnabled(true);
            }
        }
        catch (Throwable t)
        {
            JOptionPane.showMessageDialog(rootPane, "Data Kosong!", "Error", 2);
        }        
    }//GEN-LAST:event_dataPegawaiTableMouseClicked

    private void deletePegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePegawaiButtonActionPerformed
        // TODO add your handling code here:
        String id = editIdPegawaiField.getText();
        
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Apakah Kamu Yakin?", "Delete", 1);
        
        if (opsi == 0)
        {
            users.delete(id);
            pegawai.delete(id);
            JOptionPane.showMessageDialog(rootPane, "Delete Data Berhasil!", "Success", 1);

            editIdPegawaiField.setText("");
            editNamaPegawaiField.setText("");
            editAlamatPegawaiField.setText("");
            editContactPegawaiField.setText("");
            editUsernamePegawaiField.setText("");
            editPasswordPegawaiField.setText("");

            editNamaPegawaiField.setEnabled(false);
            editAlamatPegawaiField.setEnabled(false);
            editContactPegawaiField.setEnabled(false);
            editUsernamePegawaiField.setEnabled(false);
            editPasswordPegawaiField.setEnabled(false);

            editPegawaiButton.setEnabled(false);
            deletePegawaiButton.setEnabled(false);
            cancelPegawaiButton.setEnabled(false);
            tampilkan();
        }        
    }//GEN-LAST:event_deletePegawaiButtonActionPerformed

    private void dataMobilTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMobilTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dataMobilTableMouseEntered

    private void deleteMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMobilButtonActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Apakah Kamu Yakin?", "Delete", 1);
        
        if (opsi == 0)
        {
            mobil.delete(editIdMobilField.getText());
            JOptionPane.showMessageDialog(rootPane, "Delete Data Berhasil!", "Success", 1);
            
            editIdMobilField.setText("");
            editJenisMobilField.setText("");
            editSewaMobilField.setText("");                
            editStokMobilField.setText("");                

            editJenisMobilField.setEnabled(false);
            editSewaMobilField.setEnabled(false);
            editStokMobilField.setEnabled(false);                

            editMobilButton.setEnabled(false);
            deleteMobilButton.setEnabled(false);
            cancelMobilButton.setEnabled(false);
            tampilkan();
        }        
    }//GEN-LAST:event_deleteMobilButtonActionPerformed

    private void searchPegawaiFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPegawaiFieldKeyPressed
        // TODO add your handling code here:
        for (int i = 0; i < dataPegawaiTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPegawaiTable.getColumnCount(); j++)
            {
                dataPegawaiTable.setValueAt("", i, j);
            }
        }
        
        try {            
            ResultSet hasilPegawai = pegawai.searchData(searchPegawaiField.getText());            
            int row = 0;
            while (hasilPegawai.next())
            {
                dataPegawaiTable.setValueAt(hasilPegawai.getString(1), row, 0);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(2), row, 1);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(3), row, 2);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(4), row, 3);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(5), row, 4);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(6), row, 5);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(8), row, 6);
                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchPegawaiFieldKeyPressed

    private void searchMobilFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchMobilFieldKeyPressed
        // TODO add your handling code here:
        for (int i = 0; i < dataMobilTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataMobilTable.getColumnCount(); j++)
            {
                dataMobilTable.setValueAt("", i, j);
            }
        }
        
        try {            
            ResultSet hasil = mobil.searchData(searchMobilField.getText());
            int row = 0;
            while (hasil.next())
            {
                dataMobilTable.setValueAt(hasil.getString(1), row, 0);
                dataMobilTable.setValueAt(hasil.getString(2), row, 1);
                dataMobilTable.setValueAt(hasil.getString(3), row, 2);
                dataMobilTable.setValueAt(hasil.getString(4), row, 3);
                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchMobilFieldKeyPressed

    private void startup()
    {
        try {
            ResultSet hasil = pegawai.searchDataId(id);
            while (hasil.next())
            {
                data.setId(hasil.getString(1));
                data.setNama(hasil.getString(2));
                data.setAlamat(hasil.getString(3));
                data.setContact(hasil.getString(4));
            }                        
            
            greetingsText.setText("Hello, " + data.getNama());
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tampilkan()
    {
        for (int i = 0; i < dataPegawaiTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPegawaiTable.getColumnCount(); j++)
            {
                dataPegawaiTable.setValueAt("", i, j);
            }
        }
        
        for (int i = 0; i < dataMobilTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataMobilTable.getColumnCount(); j++)
            {
                dataMobilTable.setValueAt("", i, j);
            }
        }
        
        for (int i = 0; i < reportTable.getRowCount(); i++)
        {
            for (int j = 0; j < reportTable.getColumnCount(); j++)
            {
                reportTable.setValueAt("", i, j);
            }
        }
        
        try {
            ResultSet hasilPegawai = pegawai.getData();
            ResultSet hasilUsers = users.getData();
            
            int row = 0;
            while (hasilPegawai.next() && hasilUsers.next())
            {
                dataPegawaiTable.setValueAt(hasilPegawai.getString(1), row, 0);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(2), row, 1);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(3), row, 2);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(4), row, 3);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(5), row, 4);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(6), row, 5);
                dataPegawaiTable.setValueAt(hasilPegawai.getString(8), row, 6);                
                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        try {
            ResultSet hasilMobil = mobil.getData();
        
            int row = 0;
            while (hasilMobil.next())
            {
                dataMobilTable.setValueAt(hasilMobil.getString(1), row, 0);
                dataMobilTable.setValueAt(hasilMobil.getString(2), row, 1);
                dataMobilTable.setValueAt(hasilMobil.getString(3), row, 2);
                dataMobilTable.setValueAt(hasilMobil.getString(4), row, 3);
                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            ResultSet hasilPeminjaman = peminjaman.getData();
        
            int row = 0;
            while (hasilPeminjaman.next())
            {
                reportTable.setValueAt(hasilPeminjaman.getString(1), row, 0);
                reportTable.setValueAt(hasilPeminjaman.getString(3), row, 1);
                reportTable.setValueAt(hasilPeminjaman.getString(4), row, 2);
                reportTable.setValueAt(hasilPeminjaman.getString(2), row, 3);
                reportTable.setValueAt(hasilPeminjaman.getString(5), row, 4);
                reportTable.setValueAt(hasilPeminjaman.getString(6), row, 5);
                reportTable.setValueAt(hasilPeminjaman.getString(9), row, 6);
                reportTable.setValueAt(hasilPeminjaman.getString(10), row, 7);
                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatField;
    private javax.swing.JButton cancelMobilButton;
    private javax.swing.JButton cancelPegawaiButton;
    private javax.swing.JTextField contactField;
    private javax.swing.JTable dataMobilTable;
    private javax.swing.JTable dataPegawaiTable;
    private javax.swing.JButton deleteMobilButton;
    private javax.swing.JButton deletePegawaiButton;
    private javax.swing.JTextArea editAlamatPegawaiField;
    private javax.swing.JTextField editContactPegawaiField;
    private javax.swing.JTextField editIdMobilField;
    private javax.swing.JTextField editIdPegawaiField;
    private javax.swing.JTextField editJenisMobilField;
    private javax.swing.JButton editMobilButton;
    private javax.swing.JTextField editNamaPegawaiField;
    private javax.swing.JTextField editPasswordPegawaiField;
    private javax.swing.JButton editPegawaiButton;
    private javax.swing.JTextField editSewaMobilField;
    private javax.swing.JTextField editStokMobilField;
    private javax.swing.JTextField editUsernamePegawaiField;
    private javax.swing.JLabel greetingsText;
    private javax.swing.JTextField idMobilField;
    private javax.swing.JTextField idPegawaiField;
    private javax.swing.JButton insertButton;
    private javax.swing.JButton insertMobilButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jenisMobilField;
    private javax.swing.JButton logOutButton;
    private javax.swing.JTextField namaField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton refreshMobilButton;
    private javax.swing.JButton refreshPegawaiButton;
    private javax.swing.JTable reportTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetMobilButton;
    private javax.swing.JButton searchMobilButton;
    private javax.swing.JTextField searchMobilField;
    private javax.swing.JButton searchPegawaiButton;
    private javax.swing.JTextField searchPegawaiField;
    private javax.swing.JTextField sewaMobilField;
    private javax.swing.JTextField stokMobilField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
