/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentalmobil;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rentalmobil.Package.*;

/**
 *
 * @author nurka
 */
public class PegawaiPage extends javax.swing.JFrame {

    private PelangganModel pelanggan;
    private MobilModel mobil;
    private String id;
    private PeminjamanModel peminjaman;
    
    public void setId(String id)
    {
        this.id = id;
        
        setTransaction();
    }
    
    /**
     * Creates new form AdminPage
     */
    public PegawaiPage() {
        peminjaman = new PeminjamanModel();
        pelanggan = new PelangganModel();
        mobil = new MobilModel();
        this.id = "";
        initComponents();
        tampilkan();
        setTransaction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        idPelanggan = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        namaPelanggan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatPelanggan = new javax.swing.JTextArea();
        contactPelanggan = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        searchPelanggan = new javax.swing.JTextField();
        searchPelangganButton = new javax.swing.JButton();
        refreshPelangganButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        dataPelangganTable = new javax.swing.JTable();
        editIdPelangganField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        editNamaPelangganField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        editAlamatPelangganField = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        editContactPelangganField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        cancelPelangganButton = new javax.swing.JButton();
        deletePelangganButton = new javax.swing.JButton();
        editPelangganButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dataMobilTable = new javax.swing.JTable();
        searchMobilField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        searchMobilButton = new javax.swing.JButton();
        refreshMobilButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idPegawai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idPeminjaman = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        biayaSewa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        totalSewa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tanggalKembali = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jenisComBox = new javax.swing.JComboBox<>();
        dateChooser = new com.toedter.calendar.JDateChooser();
        lamaPinjam = new javax.swing.JSpinner();
        idPelangganComBox = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        idpel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        idmo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lp = new javax.swing.JTextField();
        bs = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tk = new javax.swing.JTextField();
        telat = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        denda = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        searchPeminjaman = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFocusable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setText("Welcome to User");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 140, 50));

        jTabbedPane1.addTab("Pegawai", jPanel2);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel3.setText("Input Data Pelanggan");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel20.setText("Id Pelanggan (Contoh : 001)");

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel21.setText("Nama");

        namaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPelangganActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel22.setText("Alamat");

        alamatPelanggan.setColumns(20);
        alamatPelanggan.setRows(5);
        jScrollPane1.setViewportView(alamatPelanggan);

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel23.setText("Contact");

        jButton7.setText("Insert");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(idPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23)
                                    .addComponent(contactPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(namaPelanggan)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(156, 156, 156))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Input Pelanggan", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel30.setText("DATA PELANGGAN");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 6, -1, -1));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel31.setText("Nama Pelanggan");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        searchPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchPelangganKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchPelangganKeyTyped(evt);
            }
        });
        jPanel4.add(searchPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 54, 189, 30));

        searchPelangganButton.setText("Search");
        searchPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPelangganButtonActionPerformed(evt);
            }
        });
        jPanel4.add(searchPelangganButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 55, 100, 30));

        refreshPelangganButton.setText("Refresh");
        refreshPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPelangganButtonActionPerformed(evt);
            }
        });
        jPanel4.add(refreshPelangganButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 55, 100, 30));

        dataPelangganTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataPelangganTable.setFocusable(false);
        dataPelangganTable.setVerifyInputWhenFocusTarget(false);
        dataPelangganTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPelangganTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(dataPelangganTable);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 97, 534, 392));

        editIdPelangganField.setEnabled(false);
        jPanel4.add(editIdPelangganField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 240, 30));

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel32.setText("Id Pelanggan");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 106, -1, 30));

        editNamaPelangganField.setEnabled(false);
        jPanel4.add(editNamaPelangganField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 240, 30));

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel33.setText("Nama");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 30));

        editAlamatPelangganField.setColumns(20);
        editAlamatPelangganField.setRows(5);
        editAlamatPelangganField.setEnabled(false);
        jScrollPane2.setViewportView(editAlamatPelangganField);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, -1));

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel34.setText("Alamat");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        editContactPelangganField.setEnabled(false);
        jPanel4.add(editContactPelangganField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 243, 30));

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel35.setText("Contact");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 30));

        cancelPelangganButton.setText("Cancel");
        cancelPelangganButton.setEnabled(false);
        cancelPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPelangganButtonActionPerformed(evt);
            }
        });
        jPanel4.add(cancelPelangganButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 90, 40));

        deletePelangganButton.setText("Delete");
        deletePelangganButton.setEnabled(false);
        deletePelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePelangganButtonActionPerformed(evt);
            }
        });
        jPanel4.add(deletePelangganButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 90, 40));

        editPelangganButton.setText("Edit");
        editPelangganButton.setEnabled(false);
        editPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPelangganButtonActionPerformed(evt);
            }
        });
        jPanel4.add(editPelangganButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 90, 40));

        jTabbedPane1.addTab("Data Pelanggan", jPanel4);

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel25.setText("DATA MOBIL");

        dataMobilTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Jenis", "Sewa (/hari)", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(dataMobilTable);

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel36.setText("Id Mobil");

        searchMobilButton.setText("Search");
        searchMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMobilButtonActionPerformed(evt);
            }
        });

        refreshMobilButton.setText("Refresh");
        refreshMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshMobilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel25)
                            .addGap(335, 335, 335)))
                    .addGap(12, 12, 12)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(searchMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel25)
                    .addGap(54, 54, 54)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Mobil", jPanel5);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel4.setText("Transaksi Peminjaman");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Id Pegawai");

        idPegawai.setEditable(false);
        idPegawai.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("Id Peminjaman");

        idPeminjaman.setEditable(false);
        idPeminjaman.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Id Pelanggan");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Jenis Mobil");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setText("Tanggal Pinjam");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setText("Lama Pinjam (hari)");

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        biayaSewa.setEditable(false);
        biayaSewa.setFocusable(false);

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setText("Biaya Sewa");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Total Sewa");

        totalSewa.setEditable(false);
        totalSewa.setFocusable(false);

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("Tanggal Kembali");

        tanggalKembali.setEditable(false);
        tanggalKembali.setFocusable(false);

        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(biayaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addGap(18, 18, 18))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(biayaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(totalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
        );

        jenisComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jenisComBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jenisComBoxItemStateChanged(evt);
            }
        });
        jenisComBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jenisComBoxFocusLost(evt);
            }
        });
        jenisComBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jenisComBoxPropertyChange(evt);
            }
        });

        dateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserPropertyChange(evt);
            }
        });

        lamaPinjam.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lamaPinjamStateChanged(evt);
            }
        });

        idPelangganComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idPelangganComBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idPelangganComBoxItemStateChanged(evt);
            }
        });
        idPelangganComBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idPelangganComBoxFocusLost(evt);
            }
        });
        idPelangganComBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                idPelangganComBoxPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5)
                        .addGap(339, 339, 339)
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(idPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(idPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(idPelangganComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jenisComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(321, 321, 321)
                                .addComponent(jLabel8))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(lamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(300, 300, 300)
                                .addComponent(jLabel10)))))
                .addGap(54, 54, 54))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jenisComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPelangganComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Peminjaman", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel14.setText("Transaksi Pengembalian");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, -1, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel17.setText("Id Pelanggan");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 57, -1, -1));

        idpel.setEditable(false);
        idpel.setFocusable(false);
        jPanel9.add(idpel, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 56, 240, 30));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel18.setText("Id Mobil");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 107, -1, -1));

        idmo.setEditable(false);
        idmo.setFocusable(false);
        jPanel9.add(idmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 106, 240, 30));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel19.setText("Tanggal Pinjam");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 158, -1, -1));

        tp.setEditable(false);
        tp.setFocusable(false);
        jPanel9.add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 157, 240, 30));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel24.setText("Lama Pinjam");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 208, -1, -1));

        lp.setEditable(false);
        lp.setFocusable(false);
        jPanel9.add(lp, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 207, 240, 30));

        bs.setEditable(false);
        bs.setFocusable(false);
        jPanel9.add(bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 258, 240, 30));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel26.setText("Biaya Sewa");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 259, -1, -1));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel27.setText("Tanggal Kembali");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 307, -1, -1));

        tk.setEditable(false);
        tk.setFocusable(false);
        jPanel9.add(tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 306, 240, 30));
        jPanel9.add(telat, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 56, 252, 30));

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel28.setText("Telat");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 57, -1, -1));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel29.setText("Denda");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, 40));
        jPanel9.add(denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 157, 252, 30));

        jButton3.setText("Proses");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 104, -1, 35));

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 205, -1, 35));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 97, 900, 380));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel15.setText("Id Peminjaman");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 30));

        searchPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPeminjamanActionPerformed(evt);
            }
        });
        jPanel7.add(searchPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 240, 30));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 90, 30));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel16.setText("Search Data Transaksi");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jTabbedPane1.addTab("Pengembalian", jPanel7);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("MOMOBILAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:                
        idPelanggan.setText("");
        namaPelanggan.setText("");
        alamatPelanggan.setText("");
        contactPelanggan.setText("");
        
        idPelanggan.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void namaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPelangganActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String id = idPelanggan.getText();
        String nama = namaPelanggan.getText();
        String alamat = alamatPelanggan.getText();
        String contact = contactPelanggan.getText();
        
        pelanggan.insert(id, nama, alamat, contact);
        JOptionPane.showMessageDialog(rootPane, "Insert Data Success!", "Success", 1);
        
        idPelanggan.setText("");
        namaPelanggan.setText("");
        alamatPelanggan.setText("");
        contactPelanggan.setText("");
        tampilkan();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void searchPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPelangganButtonActionPerformed
        for (int i = 0; i < dataPelangganTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPelangganTable.getColumnCount(); j++)
            {
                dataPelangganTable.setValueAt("", i, j);
            }
        }

        try {
            ResultSet hasil = pelanggan.searchData(searchPelanggan.getText());            
            while (hasil.next())
            {
                dataPelangganTable.setValueAt(hasil.getString(1), 0, 0);
                dataPelangganTable.setValueAt(hasil.getString(2), 0, 1);
                dataPelangganTable.setValueAt(hasil.getString(3), 0, 2);
                dataPelangganTable.setValueAt(hasil.getString(4), 0, 3);                
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_searchPelangganButtonActionPerformed

    private void refreshPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPelangganButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < dataPelangganTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPelangganTable.getColumnCount(); j++)
            {
                dataPelangganTable.setValueAt("", i, j);
            }
        }

        tampilkan();
    }//GEN-LAST:event_refreshPelangganButtonActionPerformed

    private void dataPelangganTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPelangganTableMouseClicked
        // TODO add your handling code here:
        try
        {
            if (evt.getClickCount() == 2)
            {
                int row = dataPelangganTable.getSelectedRow();
                editIdPelangganField.setText(dataPelangganTable.getValueAt(row, 0).toString());
                editNamaPelangganField.setText(dataPelangganTable.getValueAt(row, 1).toString());
                editAlamatPelangganField.setText(dataPelangganTable.getValueAt(row, 2).toString());
                editContactPelangganField.setText(dataPelangganTable.getValueAt(row, 3).toString());                

                editNamaPelangganField.setEnabled(true);
                editAlamatPelangganField.setEnabled(true);
                editContactPelangganField.setEnabled(true);                

                editPelangganButton.setEnabled(true);
                deletePelangganButton.setEnabled(true);
                cancelPelangganButton.setEnabled(true);
            }
        }
        catch (Throwable t)
        {
            JOptionPane.showMessageDialog(rootPane, "Data Kosong!", "Error", 2);
        }
    }//GEN-LAST:event_dataPelangganTableMouseClicked

    private void cancelPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPelangganButtonActionPerformed
        // TODO add your handling code here:
        editIdPelangganField.setText("");
        editNamaPelangganField.setText("");
        editAlamatPelangganField.setText("");
        editContactPelangganField.setText("");        

        editNamaPelangganField.setEnabled(false);
        editAlamatPelangganField.setEnabled(false);
        editContactPelangganField.setEnabled(false);        

        editPelangganButton.setEnabled(false);
        deletePelangganButton.setEnabled(false);
        cancelPelangganButton.setEnabled(false);
    }//GEN-LAST:event_cancelPelangganButtonActionPerformed

    private void deletePelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePelangganButtonActionPerformed
        // TODO add your handling code here:
        String id = editIdPelangganField.getText();

        pelanggan.delete(id);        

        editIdPelangganField.setText("");
        editNamaPelangganField.setText("");
        editAlamatPelangganField.setText("");
        editContactPelangganField.setText("");        

        editNamaPelangganField.setEnabled(false);
        editAlamatPelangganField.setEnabled(false);
        editContactPelangganField.setEnabled(false);        

        editPelangganButton.setEnabled(false);
        deletePelangganButton.setEnabled(false);
        cancelPelangganButton.setEnabled(false);
        tampilkan();
    }//GEN-LAST:event_deletePelangganButtonActionPerformed

    private void editPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPelangganButtonActionPerformed
        // TODO add your handling code here:
        String id = editIdPelangganField.getText();
        String nama = editNamaPelangganField.getText();
        String alamat = editAlamatPelangganField.getText();
        String contact = editContactPelangganField.getText();        

        pelanggan.update(id, nama, alamat, contact);

        editIdPelangganField.setText("");
        editNamaPelangganField.setText("");
        editAlamatPelangganField.setText("");
        editContactPelangganField.setText("");        

        editNamaPelangganField.setEnabled(false);
        editAlamatPelangganField.setEnabled(false);
        editContactPelangganField.setEnabled(false);        

        editPelangganButton.setEnabled(false);
        deletePelangganButton.setEnabled(false);
        cancelPelangganButton.setEnabled(false);
        tampilkan();
    }//GEN-LAST:event_editPelangganButtonActionPerformed

    private void searchMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMobilButtonActionPerformed
        for (int i = 0; i < dataMobilTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataMobilTable.getColumnCount(); j++)
            {
                dataMobilTable.setValueAt("", i, j);
            }
        }

        try {
            ResultSet hasil = mobil.searchData(searchMobilField.getText());
            while (hasil.next())
            {
                dataMobilTable.setValueAt(hasil.getString(1), 0, 0);
                dataMobilTable.setValueAt(hasil.getString(2), 0, 1);
                dataMobilTable.setValueAt(hasil.getString(3), 0, 2);
                dataMobilTable.setValueAt(hasil.getString(4), 0, 3);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchMobilButtonActionPerformed

    private void refreshMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshMobilButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < dataMobilTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataMobilTable.getColumnCount(); j++)
            {
                dataMobilTable.setValueAt("", i, j);
            }
        }

        tampilkan();
    }//GEN-LAST:event_refreshMobilButtonActionPerformed

    private void jenisComBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jenisComBoxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisComBoxPropertyChange

    private void jenisComBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jenisComBoxFocusLost
        // TODO add your handling code here:        
    }//GEN-LAST:event_jenisComBoxFocusLost

    private void jenisComBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jenisComBoxItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)
        {
            ResultSet hasil = mobil.getData();
            try {
                while (hasil.next())
                {
                    if (hasil.getString(2).equals(jenisComBox.getSelectedItem().toString()))
                    {
                        biayaSewa.setText(hasil.getString(3));
                        long totSew = Integer.parseInt(lamaPinjam.getValue().toString()) * Integer.parseInt(hasil.getString(3));
                        totalSewa.setText(String.valueOf(totSew));
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(PegawaiPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }              
    }//GEN-LAST:event_jenisComBoxItemStateChanged

    private void idPelangganComBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idPelangganComBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_idPelangganComBoxItemStateChanged

    private void idPelangganComBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idPelangganComBoxFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_idPelangganComBoxFocusLost

    private void idPelangganComBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_idPelangganComBoxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_idPelangganComBoxPropertyChange

    private void lamaPinjamStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lamaPinjamStateChanged
        // TODO add your handling code here:
        java.util.Date date = dateChooser.getDate();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(date);
        calendar.add(Calendar.DAY_OF_MONTH, Integer.parseInt(lamaPinjam.getValue().toString()));
        java.util.Date newDate = calendar.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = dateFormat.format(newDate);
        
        tanggalKembali.setText(formattedDate);
        
        long totSew = Integer.parseInt(lamaPinjam.getValue().toString()) * Integer.parseInt(biayaSewa.getText());
        totalSewa.setText(String.valueOf(totSew));
    }//GEN-LAST:event_lamaPinjamStateChanged

    private void dateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserPropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName()))
        {
            java.util.Date date = dateChooser.getDate();
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(date);
            calendar.add(Calendar.DAY_OF_MONTH, Integer.parseInt(lamaPinjam.getValue().toString()));
            java.util.Date newDate = calendar.getTime();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = dateFormat.format(newDate);

            tanggalKembali.setText(formattedDate);
        }
    }//GEN-LAST:event_dateChooserPropertyChange

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dateChooser.setDate(new java.util.Date());
        lamaPinjam.setValue(0);
        idPelangganComBox.setSelectedIndex(0);
        jenisComBox.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void searchPelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPelangganKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchPelangganKeyTyped

    private void searchPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPelangganKeyPressed
        // TODO add your handling code here:
        for (int i = 0; i < dataPelangganTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPelangganTable.getColumnCount(); j++)
            {
                dataPelangganTable.setValueAt("", i, j);
            }
        }

        int row = 0;
        try {
            ResultSet hasil = pelanggan.searchData(searchPelanggan.getText());    
                        
            while (hasil.next())
            {
                dataPelangganTable.setValueAt(hasil.getString(1), row, 0);
                dataPelangganTable.setValueAt(hasil.getString(2), row, 1);
                dataPelangganTable.setValueAt(hasil.getString(3), row, 2);
                dataPelangganTable.setValueAt(hasil.getString(4), row, 3);  
                
                row++;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_searchPelangganKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String id = idPeminjaman.getText();
        String idPeg = idPegawai.getText();
        String idPel = idPelangganComBox.getSelectedItem().toString();
        String idMo = "";
        ResultSet hasil = mobil.getData();
        try {
            while (hasil.next())
            {
                if (hasil.getString(2).equals(jenisComBox.getSelectedItem().toString()))
                {
                    idMo = hasil.getString(1);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(PegawaiPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.util.Date date = dateChooser.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = dateFormat.format(date);
        String tglPinjam = formattedDate;
        String tglKembali = tanggalKembali.getText();
        int lama = Integer.parseInt(lamaPinjam.getValue().toString());
        String biaya = totalSewa.getText();
        
        peminjaman.insert(id, idPeg, idPel, idMo, tglPinjam, tglKembali, lama, 0, biaya, "10000");
        JOptionPane.showMessageDialog(rootPane, "Peminjaman Berhasil!", "Success", 1);
        setTransaction();
        dateChooser.setDate(new java.util.Date());
        lamaPinjam.setValue(0);
        idPelangganComBox.setSelectedIndex(0);
        jenisComBox.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void searchPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPeminjamanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id = searchPeminjaman.getText();
        
        ResultSet hasil = peminjaman.searchData(id);
        
        try {
            while (hasil.next())
            {
                idpel.setText(hasil.getString(3));
                idmo.setText(hasil.getString(4));
                tp.setText(hasil.getString(5));
                lp.setText(String.valueOf(hasil.getInt(7)));
                bs.setText(hasil.getString(9));
                tk.setText(hasil.getString(6));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PegawaiPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (telat.getText() == "0")
        {
            denda.setText("0");
            telat.setEnabled(false);
        }
        else
        {            
            int tlt = Integer.parseInt(telat.getText());
            long biaya = 10000;
            
            long dnd = tlt * biaya;
            
            denda.setText(String.valueOf(dnd));
            telat.setEnabled(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id = searchPeminjaman.getText();
        peminjaman.update(id, Integer.parseInt(telat.getText()), denda.getText());
        
        JOptionPane.showMessageDialog(rootPane, "Berhasil Simpan!", "Success", 1);
        searchPeminjaman.setText("");
        idpel.setText("");
        idmo.setText("");
        tp.setText("");
        lp.setText("");
        bs.setText("");
        tk.setText("");
        telat.setEnabled(true);
        telat.setText("");
        denda.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tampilkan()
    {
        for (int i = 0; i < dataPelangganTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPelangganTable.getColumnCount(); j++)
            {
                dataPelangganTable.setValueAt("", i, j);
            }
        }
        
        for (int i = 0; i < dataMobilTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataMobilTable.getColumnCount(); j++)
            {
                dataMobilTable.setValueAt("", i, j);
            }
        }
        
        ResultSet hasil = pelanggan.getData();
        int row = 0;        
        
        try {
            while (hasil.next())
            {                
                dataPelangganTable.setValueAt(hasil.getString(1), row, 0);                
                dataPelangganTable.setValueAt(hasil.getString(2), row, 1);                
                dataPelangganTable.setValueAt(hasil.getString(3), row, 2);                
                dataPelangganTable.setValueAt(hasil.getString(4), row, 3);                
                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(PegawaiPage.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        try {
            ResultSet hasilMobil = mobil.getData();
        
            row = 0;
            while (hasilMobil.next())
            {
                dataMobilTable.setValueAt(hasilMobil.getString(1), row, 0);
                dataMobilTable.setValueAt(hasilMobil.getString(2), row, 1);
                dataMobilTable.setValueAt(hasilMobil.getString(3), row, 2);
                dataMobilTable.setValueAt(hasilMobil.getString(4), row, 3);
                                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setTransaction()
    {
        dateChooser.setDate(new java.util.Date());
        String id = getRandomId();
        idPeminjaman.setText(id);
        idPegawai.setText(this.id);
        
        jenisComBox.removeAllItems();
        idPelangganComBox.removeAllItems();
        try {
            ResultSet hasil = pelanggan.getData();
                    
            while (hasil.next())
            {                              
                idPelangganComBox.addItem(hasil.getString(1));                
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            ResultSet hasilMobil = mobil.getData();
                    
            while (hasilMobil.next())
            {                              
                jenisComBox.addItem(hasilMobil.getString(2));                
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private String getRandomId()
    {
        String huruf = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String angka = "0123456789";
        String randomId = "";
        
        for (int i = 0; i < 3; i++)
        {
            randomId += huruf.charAt((int) (Math.random() * huruf.length()));
            randomId += angka.charAt((int) (Math.random() * angka.length()));
        }
                
        return randomId;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PegawaiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PegawaiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PegawaiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PegawaiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PegawaiPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatPelanggan;
    private javax.swing.JTextField biayaSewa;
    private javax.swing.JTextField bs;
    private javax.swing.JButton cancelPelangganButton;
    private javax.swing.JTextField contactPelanggan;
    private javax.swing.JTable dataMobilTable;
    private javax.swing.JTable dataPelangganTable;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton deletePelangganButton;
    private javax.swing.JTextField denda;
    private javax.swing.JTextArea editAlamatPelangganField;
    private javax.swing.JTextField editContactPelangganField;
    private javax.swing.JTextField editIdPelangganField;
    private javax.swing.JTextField editNamaPelangganField;
    private javax.swing.JButton editPelangganButton;
    private javax.swing.JTextField idPegawai;
    private javax.swing.JTextField idPelanggan;
    private javax.swing.JComboBox<String> idPelangganComBox;
    private javax.swing.JTextField idPeminjaman;
    private javax.swing.JTextField idmo;
    private javax.swing.JTextField idpel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jenisComBox;
    private javax.swing.JSpinner lamaPinjam;
    private javax.swing.JTextField lp;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JButton refreshMobilButton;
    private javax.swing.JButton refreshPelangganButton;
    private javax.swing.JButton searchMobilButton;
    private javax.swing.JTextField searchMobilField;
    private javax.swing.JTextField searchPelanggan;
    private javax.swing.JButton searchPelangganButton;
    private javax.swing.JTextField searchPeminjaman;
    private javax.swing.JTextField tanggalKembali;
    private javax.swing.JTextField telat;
    private javax.swing.JTextField tk;
    private javax.swing.JTextField totalSewa;
    private javax.swing.JTextField tp;
    // End of variables declaration//GEN-END:variables
}
